---
- name: Install apache and php in Redhat
  become: yes
  hosts: localhost
  tasks:
    - name: install apache
      ansible.builtin.dnf:
        name:
          - httpd
          - php
          - php-cli 
          - php-common
        state: present
    - name: create info.php
      ansible.builtin.copy:
        content: '<?php phpinfo(); ?>'
        dest: /var/www/html/info.php
    - name: ensure httpd is running
      ansible.builtin.service:
        name: httpd
        enabled: yes
        state: started
